Roles and privileges - Counselling is dependent on ART
METS-Programme/openmrs-module-ugandaemr-poc pull request #109
Opened 2020-03-23 10:27 UTC by solemabrothers

https://app.asana.com/0/1133167201254913/1166217269516324

2020-03-26 09:33 UTC, dbaluku commented
@solemabrothers  what qualifies the client to move to the 'attended to' list in the counselling page

2020-03-26 10:03 UTC, solemabrothers commented
> 
> 
> @solemabrothers what qualifies the client to move to the 'attended to' list in the counselling page

The Provider completes a patient session

2020-03-27 04:08 UTC, slubwama requested changes

2020-03-27 04:08 UTC, slubwama commented on omod/src/main/resources/apps/poc_homepage_app.json
> +        "id": "ugandaemr.mch.homepageLink",
@solemabrothers Why ugandaemr.mch.homepageLink

2020-03-27 05:32 UTC, solemabrothers commented on omod/src/main/resources/apps/poc_homepage_app.json
> +        "id": "ugandaemr.mch.homepageLink",
This was over sight, the change has been made

2020-03-27 05:35 UTC, slubwama approved these changes

2020-03-30 06:05 UTC, merged